<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130325135351 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Page ADD slug VARCHAR(255) DEFAULT NULL");
        $this->addSql("ALTER TABLE Site ADD body_color VARCHAR(10) NOT NULL, ADD header_color VARCHAR(10) NOT NULL, ADD footer_color VARCHAR(10) NOT NULL, ADD font_color VARCHAR(10) NOT NULL");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Page DROP slug");
        $this->addSql("ALTER TABLE Site DROP body_color, DROP header_color, DROP footer_color, DROP font_color");
    }
}
