<?php

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130325131018 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Page ADD parent_id INT DEFAULT NULL");
        $this->addSql("ALTER TABLE Page ADD CONSTRAINT FK_B438191E727ACA70 FOREIGN KEY (parent_id) REFERENCES Page (id)");
        $this->addSql("CREATE INDEX IDX_B438191E727ACA70 ON Page (parent_id)");
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
        
        $this->addSql("ALTER TABLE Page DROP FOREIGN KEY FK_B438191E727ACA70");
        $this->addSql("DROP INDEX IDX_B438191E727ACA70 ON Page");
        $this->addSql("ALTER TABLE Page DROP parent_id");
    }
}
